apiVersion: v1
kind: Service
metadata:
  labels:
    app: sim-exp
  name: sim-exp-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/sim-exp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sim-exp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
